In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

In [33]:
#Reading the data ignoring first 28 rows
main_df = pd.read_excel("weather_dataset_stage1.xls", skiprows = 28)
print(main_df)

             Date  Temperature  Average humidity (%  Average dewpoint (°F  \
0      2022-01-01       '37.8'               '35.0'                '12.7'
1     2022-01-02'       '43.2'               '32.0'                '14.7'
2     2022-01-03'       '25.7'               '60.0'                '12.7'
3     2022-01-04'        '9.3'               '67.0'                 '0.1'
4     2022-01-05'       '23.5'               '30.0'                '-5.3'
...           ...          ...                  ...                   ...
3898  2022-07-25'       '62.8'               '60.0'                '48.1'
3899  2022-07-26'       '60.6'               '68.0'                '48.9'
3900  2022-07-27'       '61.7'               '64.0'                '47.4'
3901  2022-07-28'       '60.5'               '61.0'                '45.3'
3902  2022-07-28'       '60.5'               '61.0'                '45.3'

      Average barometer (in  Average windspeed (mph  Average gustspeed (mph  \
0                    '29.7'                  '26.4'                  '36.8'
1                    '29.5'                  '12.8'                  '18.0'
2                    '29.7'                   '8.3'                  '12.2'
3                    '30.4'                   '2.9'                   '4.5'
4                    '29.9'                  '16.7'                  '23.1'
...                     ...                     ...                     ...
3898                 '29.7'                   '2.5'                   '4.0'
3899                 '29.8'                   '1.7'                   '2.9'
3900                 '29.9'                   '2.2'                   '4.0'
3901                 '29.7'                   '4.0'                   '6.2'
3902                 '29.7'                   '4.0'                   '6.2'

      Average direction (°deg  Rainfall for month (in Rainfall for year (in  \
0                     '274.0'                   '0.0'                 '0.0'
1                     '240.0'                   '0.0'                 '0.0'
2                     '290.0'                   '0.0'                 '0.0'
3                      '47.0'                   '0.0'                 '0.0'
4                     '265.0'                   '0.0'                 '0.0'
...                       ...                     ...                   ...
3898                  '242.0'                  '0.33'                '4.47'
3899                  '357.0'                  '0.33'                '4.47'
3900                   '66.0'                  '0.33'                '4.47'
3901                  '248.0'                  '0.35'                '4.49'
3902                  '248.0'                  '0.35'                '4.49'

      ...  Maximum humidity (%  Minimum humidity (%  Maximum pressure  \
0     ...                '4.0'               '27.0'          '29.762'
1     ...                '4.0'               '16.0'          '29.669'
2     ...                '8.0'               '35.0'          '30.232'
3     ...                '7.0'               '35.0'          '30.566'
4     ...                '5.0'               '13.0'          '30.233'
...   ...                  ...                  ...               ...
3898  ...               '90.0'               '36.0'          '29.781'
3899  ...               '90.0'               '40.0'           '29.93'
3900  ...               '96.0'               '35.0'          '29.941'
3901  ...               '94.0'               '35.0'          '29.792'
3902  ...               '94.0'               '35.0'          '29.792'

      Minimum pressure  Maximum windspeed (mph  Maximum gust speed (mph  \
0             '29.596'                  '41.4'                   '59.0'
1             '29.268'                  '35.7'                   '51.0'
2              '29.26'                  '25.3'                   '38.0'
3             '30.227'                  '12.7'                   '20.0'
4             '29.568'                  '38.0'                   '53.0'
...                ...                     ...                      ...
3898          '29.645'                   '8.1'                   '17.3'
3899          '29.745'                  '11.5'                   '15.0'
3900          '29.781'                  '13.8'                   '18.4'
3901          '29.675'                  '17.3'                   '26.5'
3902          '29.675'                  '17.3'                   '26.5'

      Maximum heat index (°F         Date1  Month           diff_pressure
0                     '40.0'  '2022-01-01'   '01'   '0.16600000000000037'
1                     '52.0'  '2022-01-02'   '01'    '0.4009999999999998'
2                     '41.0'  '2022-01-03'   '01'    '0.9719999999999978'
3                     '32.0'  '2022-01-04'   '01'   '0.33899999999999864'
4                     '32.0'  '2022-01-05'   '01'    '0.6649999999999991'
...                      ...           ...    ...                     ...
3898                  '77.5'  '2022-07-25'   '07'   '0.13599999999999923'
3899                  '77.5'  '2022-07-26'   '07'   '0.18499999999999872'
3900                  '78.2'  '2022-07-27'   '07'   '0.16000000000000014'
3901                  '77.6'  '2022-07-28'   '07'  '0.11700000000000088';
3902                  '77.6'  '2022-07-28'   '07'  '0.11700000000000088';

[3903 rows x 23 columns]

In [34]:
#Column headers
main_df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype='object')

In [35]:
#removing unnecessary columns
main_df = main_df.drop(main_df.loc[:, 'Date1':' diff_pressure'].columns, axis=1)

In [36]:
main_df

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0','0.0','40.0','34.0','4.0','27.0','29.762','29.596','41.4','59.0','40.0'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0','0.0','52.0','37.0','4.0','16.0','29.669','29.268','35.7','51.0','52.0'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0','0.0','41.0','6.0','8.0','35.0','30.232','29.26','25.3','38.0','41.0'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0','0.0','19.0','-0.0','7.0','35.0','30.566','30.227','12.7','20.0','32.0'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0','0.0','30.0','15.0','5.0','13.0','30.233','29.568','38.0','53.0','32.0'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3898,2022-07-25','62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47','0.0','69.2','55.1','90.0','36.0','29.781','29.645','8.1','17.3','77.5'
3899,2022-07-26','60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47','0.0','71.9','50.5','90.0','40.0','29.93','29.745','11.5','15.0','77.5'
3900,2022-07-27','61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47','0.0','77.3','43.6','96.0','35.0','29.941','29.781','13.8','18.4','78.2'
3901,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49','0.0','75.6','46.0','94.0','35.0','29.792','29.675','17.3','26.5','77.6'
3902,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49','0.0','75.6','46.0','94.0','35.0','29.792','29.675','17.3','26.5','77.6'

In [37]:
#remove the character " ' " from the dataframe
main_df = main_df.applymap(lambda x: x.replace("'", ''))
#main_df = main_df.replace(to_replace="'", value='')
print(main_df)

            Date  Temperature  Average humidity (%  Average dewpoint (°F  \
0     2022-01-01         37.8                 35.0                  12.7
1     2022-01-02         43.2                 32.0                  14.7
2     2022-01-03         25.7                 60.0                  12.7
3     2022-01-04          9.3                 67.0                   0.1
4     2022-01-05         23.5                 30.0                  -5.3
...          ...          ...                  ...                   ...
3898  2022-07-25         62.8                 60.0                  48.1
3899  2022-07-26         60.6                 68.0                  48.9
3900  2022-07-27         61.7                 64.0                  47.4
3901  2022-07-28         60.5                 61.0                  45.3
3902  2022-07-28         60.5                 61.0                  45.3

      Average barometer (in  Average windspeed (mph  Average gustspeed (mph  \
0                      29.7                    26.4                    36.8
1                      29.5                    12.8                    18.0
2                      29.7                     8.3                    12.2
3                      30.4                     2.9                     4.5
4                      29.9                    16.7                    23.1
...                     ...                     ...                     ...
3898                   29.7                     2.5                     4.0
3899                   29.8                     1.7                     2.9
3900                   29.9                     2.2                     4.0
3901                   29.7                     4.0                     6.2
3902                   29.7                     4.0                     6.2

      Average direction (°deg  Rainfall for month (in Rainfall for year (in  \
0                       274.0                     0.0                   0.0
1                       240.0                     0.0                   0.0
2                       290.0                     0.0                   0.0
3                        47.0                     0.0                   0.0
4                       265.0                     0.0                   0.0
...                       ...                     ...                   ...
3898                    242.0                    0.33                  4.47
3899                    357.0                    0.33                  4.47
3900                     66.0                    0.33                  4.47
3901                    248.0                    0.35                  4.49
3902                    248.0                    0.35                  4.49

      Maximum rain per minute  Maximum temperature (°F  \
0                         0.0                     40.0
1                         0.0                     52.0
2                         0.0                     41.0
3                         0.0                     19.0
4                         0.0                     30.0
...                       ...                      ...
3898                      0.0                     69.2
3899                      0.0                     71.9
3900                      0.0                     77.3
3901                      0.0                     75.6
3902                      0.0                     75.6

      Minimum temperature (°F  Maximum humidity (%  Minimum humidity (%  \
0                        34.0                  4.0                 27.0
1                        37.0                  4.0                 16.0
2                         6.0                  8.0                 35.0
3                        -0.0                  7.0                 35.0
4                        15.0                  5.0                 13.0
...                       ...                  ...                  ...
3898                     55.1                 90.0                 36.0
3899                     50.5                 90.0                 40.0
3900                     43.6                 96.0                 35.0
3901                     46.0                 94.0                 35.0
3902                     46.0                 94.0                 35.0

      Maximum pressure  Minimum pressure  Maximum windspeed (mph  \
0               29.762            29.596                    41.4
1               29.669            29.268                    35.7
2               30.232             29.26                    25.3
3               30.566            30.227                    12.7
4               30.233            29.568                    38.0
...                ...               ...                     ...
3898            29.781            29.645                     8.1
3899             29.93            29.745                    11.5
3900            29.941            29.781                    13.8
3901            29.792            29.675                    17.3
3902            29.792            29.675                    17.3

      Maximum gust speed (mph  Maximum heat index (°F
0                        59.0                    40.0
1                        51.0                    52.0
2                        38.0                    41.0
3                        20.0                    32.0
4                        53.0                    32.0
...                       ...                     ...
3898                     17.3                    77.5
3899                     15.0                    77.5
3900                     18.4                    78.2
3901                     26.5                    77.6
3902                     26.5                    77.6

[3903 rows x 20 columns]

In [38]:
#changing the column name of temperature to Average Temperature
main_df = main_df.rename(columns={' Temperature' : 'Average temperature (°F)'})
main_df

,Date,Average temperature (°F),Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3898,2022-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5
3899,2022-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.93,29.745,11.5,15.0,77.5
3900,2022-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2
3901,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6
3902,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6

In [39]:
#Trim blank spaces from column headers
main_df.columns = main_df.columns.str.strip()
main_df.columns

Index(['Date', 'Average temperature (°F)', 'Average humidity (%',
       'Average dewpoint (°F', 'Average barometer (in',
       'Average windspeed (mph', 'Average gustspeed (mph',
       'Average direction (°deg', 'Rainfall for month (in',
       'Rainfall for year (in', 'Maximum rain per minute',
       'Maximum temperature (°F', 'Minimum temperature (°F',
       'Maximum humidity (%', 'Minimum humidity (%', 'Maximum pressure',
       'Minimum pressure', 'Maximum windspeed (mph', 'Maximum gust speed (mph',
       'Maximum heat index (°F'],
      dtype='object')

In [40]:
#check and fix unclosed parenthesis in the column headers
for col in main_df.columns:
    if col.count('(') != col.count(')'):
        main_df = main_df.rename(columns={col : col+ ')'})
main_df.columns
#main_df.columns = [main_df.rename(columns={col : col+ ')'}) if col.count('(') != col.count(')') else col for col in main_df.columns]

Index(['Date', 'Average temperature (°F)', 'Average humidity (%)',
       'Average dewpoint (°F)', 'Average barometer (in)',
       'Average windspeed (mph)', 'Average gustspeed (mph)',
       'Average direction (°deg)', 'Rainfall for month (in)',
       'Rainfall for year (in)', 'Maximum rain per minute',
       'Maximum temperature (°F)', 'Minimum temperature (°F)',
       'Maximum humidity (%)', 'Minimum humidity (%)', 'Maximum pressure',
       'Minimum pressure', 'Maximum windspeed (mph)',
       'Maximum gust speed (mph)', 'Maximum heat index (°F)'],
      dtype='object')

In [41]:
#check for null values in each column
nullColumn = main_df.columns[main_df.isnull().any()].tolist()

if nullColumn:
    print("columns with null values: ", nullColumn)
else:
    print("No null values")

No null values

In [42]:
#check for duplicate values in each column
for col in main_df.columns:
    print(f"Duplicate values in '{col}':{main_df[col].duplicated().sum()}")

Duplicate values in 'Date':3537
Duplicate values in 'Average temperature (°F)':3247
Duplicate values in 'Average humidity (%)':3817
Duplicate values in 'Average dewpoint (°F)':3265
Duplicate values in 'Average barometer (in)':3881
Duplicate values in 'Average windspeed (mph)':3697
Duplicate values in 'Average gustspeed (mph)':3571
Duplicate values in 'Average direction (°deg)':3574
Duplicate values in 'Rainfall for month (in)':3669
Duplicate values in 'Rainfall for year (in)':3104
Duplicate values in 'Maximum rain per minute':3902
Duplicate values in 'Maximum temperature (°F)':3223
Duplicate values in 'Minimum temperature (°F)':3326
Duplicate values in 'Maximum humidity (%)':3811
Duplicate values in 'Minimum humidity (%)':3814
Duplicate values in 'Maximum pressure':2856
Duplicate values in 'Minimum pressure':2841
Duplicate values in 'Maximum windspeed (mph)':3840
Duplicate values in 'Maximum gust speed (mph)':3799
Duplicate values in 'Maximum heat index (°F)':3277

In [43]:
#Converting the data types of columns
main_df = main_df.astype({"Date":"datetime64","Average temperature (°F)":"float64","Average humidity (%)":"float64","Average dewpoint (°F)":"float64",\
                          "Average barometer (in)":"float64","Average windspeed (mph)":"float64","Average gustspeed (mph)":"float64",\
                          "Average direction (°deg)":"float64","Rainfall for month (in)":"float64","Rainfall for year (in)":"float64",\
                          "Maximum rain per minute":"float64","Maximum temperature (°F)":"float64","Minimum temperature (°F)":"float64",\
                          "Maximum humidity (%)":"float64","Minimum humidity (%)":"float64","Maximum pressure":"float64",\
                          "Minimum pressure":"float64","Maximum windspeed (mph)":"float64","Maximum gust speed (mph)":"float64",\
                          "Maximum heat index (°F)":"float64"}, errors='ignore')
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3903 non-null   object
 1   Average temperature (°F)  3903 non-null   float64
 2   Average humidity (%)      3903 non-null   float64
 3   Average dewpoint (°F)     3903 non-null   float64
 4   Average barometer (in)    3903 non-null   float64
 5   Average windspeed (mph)   3903 non-null   float64
 6   Average gustspeed (mph)   3903 non-null   float64
 7   Average direction (°deg)  3903 non-null   float64
 8   Rainfall for month (in)   3903 non-null   float64
 9   Rainfall for year (in)    3903 non-null   float64
 10  Maximum rain per minute   3903 non-null   float64
 11  Maximum temperature (°F)  3903 non-null   float64
 12  Minimum temperature (°F)  3903 non-null   float64
 13  Maximum humidity (%)      3903 non-null   float64
 14  Minimum humidity (%)      3903 non-null   float64
 15  Maximum pressure          3903 non-null   float64
 16  Minimum pressure          3903 non-null   float64
 17  Maximum windspeed (mph)   3903 non-null   float64
 18  Maximum gust speed (mph)  3903 non-null   float64
 19  Maximum heat index (°F)   3903 non-null   float64
dtypes: float64(19), object(1)
memory usage: 610.0+ KB

In [44]:
from datetime import date
d1 = date(2022,1,1)
d2 = date(2033,7,31)
delta = d2 - d1
print(delta.days)

4229

In [45]:
#slicing year, month, date into new columns
new_column = main_df['Date'].str[0:4]
new_column2 = main_df['Date'].str[5:7]
new_column3 = main_df['Date'].str[8:]
main_df['Year'] = new_column
main_df['Month'] = new_column2
main_df['Day'] = new_column3
main_df

,Date,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Year,Month,Day
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,...,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022,01,01
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,...,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022,01,02
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,...,8.0,35.0,30.232,29.260,25.3,38.0,41.0,2022,01,03
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,...,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022,01,04
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,...,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3898,2022-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,...,90.0,36.0,29.781,29.645,8.1,17.3,77.5,2022,07,25
3899,2022-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,...,90.0,40.0,29.930,29.745,11.5,15.0,77.5,2022,07,26
3900,2022-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,...,96.0,35.0,29.941,29.781,13.8,18.4,78.2,2022,07,27
3901,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,94.0,35.0,29.792,29.675,17.3,26.5,77.6,2022,07,28
3902,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,94.0,35.0,29.792,29.675,17.3,26.5,77.6,2022,07,28

In [46]:
subset = main_df.loc[:,['Day','Month','Year']]
increment = 2022
for i in range(1, len(subset)):
    if subset.loc[i,'Month'] == '01':
        if subset.loc[i-1,'Month'] == '12' or subset.loc[i-1,'Month'] == '11':
            increment += 1
    subset.loc[i,'Year'] = increment
subset

     Day Month  Year
0     01    01  2022
1     02    01  2022
2     03    01  2022
3     04    01  2022
4     05    01  2022
...   ..   ...   ...
3898  25    07  2033
3899  26    07  2033
3900  27    07  2033
3901  28    07  2033
3902  28    07  2033

[3903 rows x 3 columns]

In [47]:
#search for non leap years
unique_years = subset['Year'].unique()

# Function to check if a year is a leap year or not
def NotLeapYear(input_year):
    if ((input_year % 400 == 0) or ((input_year % 4 == 0) and (input_year % 100 != 0))):
        return None
    else:
        return input_year

# List to store non-leap years
nonleap_years = []

# Iterate over the unique years
for i in unique_years:
    year = int(i)
    result = NotLeapYear(year)
    if result is not None:
        nonleap_years.append(result)

# Filter the DataFrame to include only rows where the day is 29, the month is 2, and the year is in nonleap_years
filtered_df = subset[(subset['Day'] == '29') & (subset['Month'] == '02') & (subset['Year'].isin(nonleap_years))]

# Replace the 29 values with 28 in the original DataFrame
subset.loc[filtered_df.index, 'Day'] = 28


# Verify that the replacement was successful
''' 
verification_df = subset.loc[(subset['Day'] == 29) & (subset['Month'] == 2) & (subset['Year'].isin(nonleap_years))]
if verification_df.empty:
    print("All 29 values in the 'Day' column for 2 in the 'Month' column in a non-leap year have been replaced with 28.")
else:
    print("Some or all 29 values in the 'Day' column for 2 in the 'Month' column in a non-leap year have not been replaced with 28.")'''


subset['Day'] = subset['Day'].astype(str)
subset['Month'] = subset['Month'].astype(str)
subset['Year'] = subset['Year'].astype(str)
#Merge Day, month, Year
subset['Date'] = subset['Year'] + '-' + subset['Month'] + '-' + subset['Day']
#changing the format to date
'''for i in subset['Date']:
    if i == '2029-02-29':
        print('True')'''

subset['Date'] =pd.to_datetime(subset['Date'])

main_df = main_df.drop(main_df.loc[:, 'Year':'Day'].columns, axis=1)

In [48]:
#correcting the dates of the main table
main_df['Date'] = subset['Date']

In [49]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3903 non-null   datetime64[ns]
 1   Average temperature (°F)  3903 non-null   float64
 2   Average humidity (%)      3903 non-null   float64
 3   Average dewpoint (°F)     3903 non-null   float64
 4   Average barometer (in)    3903 non-null   float64
 5   Average windspeed (mph)   3903 non-null   float64
 6   Average gustspeed (mph)   3903 non-null   float64
 7   Average direction (°deg)  3903 non-null   float64
 8   Rainfall for month (in)   3903 non-null   float64
 9   Rainfall for year (in)    3903 non-null   float64
 10  Maximum rain per minute   3903 non-null   float64
 11  Maximum temperature (°F)  3903 non-null   float64
 12  Minimum temperature (°F)  3903 non-null   float64
 13  Maximum humidity (%)      3903 non-null   float64
 14  Minimum humidity (%)      3903 non-null   float64
 15  Maximum pressure          3903 non-null   float64
 16  Minimum pressure          3903 non-null   float64
 17  Maximum windspeed (mph)   3903 non-null   float64
 18  Maximum gust speed (mph)  3903 non-null   float64
 19  Maximum heat index (°F)   3903 non-null   float64
dtypes: datetime64[ns](1), float64(19)
memory usage: 610.0 KB

In [54]:
#Saving the cleaned dataframe to a csv file
main_df.to_csv('cleaned_weather_dataset.csv',index = False)

In [52]:
def remove_duplicates_from_date_column(df, column_name):
  df.drop_duplicates(subset=[column_name], keep='last', inplace=True)

remove_duplicates_from_date_column(main_df, 'Date')
main_df

,Date,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,0.0,41.0,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,0.0,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4
3898,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5
3899,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5
3900,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2
3902,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6